# fly.toml app configuration file generated for movie-list on 2024-02-25T15:10:24-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'movie-list'
primary_region = 'yyz'

[env]
  PORT = "3000"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[deploy]
  strategy = "bluegreen"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
