########### movie-api
### get all movies
GET http://localhost:3001/api/movies

### search movie by title
GET http://localhost:3001/api/movies?title=brave

### search movie by title and year
GET http://localhost:3001/api/movies?title=brave&year=2012

### search movie by title or director or actor
GET http://localhost:3001/api/movies?query=brave

### get movie by imdbId
GET http://localhost:3001/api/movies/tt1217209

### get movies by a list of imdbIds
POST http://localhost:3001/api/movies/search
Content-Type: application/json

{
    "imdbIds": ["tt0112573", "tt1217209"]
}

### post movie
POST http://localhost:3001/api/movies
Content-Type: application/json

{
    "imdbId": "tt0112573",
    "title": "Braveheart"
}


########### user-api
### get user
GET http://localhost:3001/api/users/

### post  user
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "user",
    "password": "pass"
}

### update user
PUT http://localhost:3001/api/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6MSwiaWF0IjoxNzA1NjQ1ODY4LCJleHAiOjE3MDYyNTA2Njh9.h6RYmV_JOi6bpp2hJ0R0nMhELmYxiRrjP8y9FSo5X-Q

{
    "username": "user",
    "password": "pass"
}

### delete user
DELETE http://localhost:3001/api/users/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6NiwiaWF0IjoxNzA1NjQ2OTMxLCJleHAiOjE3MDYyNTE3MzF9.BApNfQ4mx2gs8eK3x75abBrDPZmbEef8TXAL4lmxpco

### login
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "user",
    "password": "pass"
}

############## movieList-api
### get defaufault movieLists
GET http://localhost:3001/api/movieLists/default

### get public movieLists
GET http://localhost:3001/api/movieLists/public

### get all movieLists (public and private) of a user
GET http://localhost:3001/api/movieLists/private
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6NywiaWF0IjoxNzA1NjQ3NjE4LCJleHAiOjE3MDYyNTI0MTh9.xNE-C3X0qCB7saV6E5tCFHTaQ7aFRBniF5qp38-LnrY

### get watchlist of a user
GET http://localhost:3001/api/movieLists/watchlist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6NywiaWF0IjoxNzA1NjQ3NjE4LCJleHAiOjE3MDYyNTI0MTh9.xNE-C3X0qCB7saV6E5tCFHTaQ7aFRBniF5qp38-LnrY

### get watched movieLists of a user
GET http://localhost:3001/api/movieLists/watched
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6NywiaWF0IjoxNzA1NjQ3NjE4LCJleHAiOjE3MDYyNTI0MTh9.xNE-C3X0qCB7saV6E5tCFHTaQ7aFRBniF5qp38-LnrY

### get publice movieList by id
GET http://localhost:3001/api/movieLists/1

### get private movieList by id
GET http://localhost:3001/api/movieLists/40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6NywiaWF0IjoxNzA1NjQ3NjE4LCJleHAiOjE3MDYyNTI0MTh9.xNE-C3X0qCB7saV6E5tCFHTaQ7aFRBniF5qp38-LnrY

### post movieList
POST http://localhost:3001/api/movieLists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6NywiaWF0IjoxNzA1NjQ3NjE4LCJleHAiOjE3MDYyNTI0MTh9.xNE-C3X0qCB7saV6E5tCFHTaQ7aFRBniF5qp38-LnrY
Content-Type: application/json

{
    "name": "list1",
    "imdbIds": [
        "tt1217209",
        "tt0112573"
    ],
    "type": "public"
}

### update movieList
PUT http://localhost:3001/api/movieLists/42
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6NywiaWF0IjoxNzA1NjQ3NjE4LCJleHAiOjE3MDYyNTI0MTh9.xNE-C3X0qCB7saV6E5tCFHTaQ7aFRBniF5qp38-LnrY
Content-Type: application/json

{
    "name": "new list",
    "imdbIds": [
        "tt0112573",
        "tt1217209"

    ],
    "type": "public"
}

### delete movieList
DELETE http://localhost:3001/api/movieLists/42
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6NywiaWF0IjoxNzA1NjQ3NjE4LCJleHAiOjE3MDYyNTI0MTh9.xNE-C3X0qCB7saV6E5tCFHTaQ7aFRBniF5qp38-LnrY
